app/models.py
from .import db
from flask.app import Flask
from flask_login import UserMixin
from sqlalchemy.sql import func
from werkzeug.security import generate_password_hash,check_password_hash
from datetime import datetime
from flask_sqlalchemy import SQLAlchemy
from . import login_manager



@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    username = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    posts = db.relationship('Post', backref='user', passive_deletes=True)
    comments = db.relationship('Comment', backref='user', passive_deletes=True)
    likes = db.relationship('Like', backref='user', passive_deletes=True)




class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text, nullable=False)
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    author = db.Column(db.Integer, db.ForeignKey('user.id', ondelete="CASCADE"), nullable=False)
    comments = db.relationship('Comment', backref='post', passive_deletes=True)
    likes = db.relationship('Like', backref='post', passive_deletes=True)


class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(200), nullable=False)
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    author = db.Column(db.Integer, db.ForeignKey('user.id', ondelete="CASCADE"), nullable=False)
    post_id = db.Column(db.Integer, db.ForeignKey('post.id', ondelete="CASCADE"), nullable=False)
        



class Like(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    author = db.Column(db.Integer, db.ForeignKey('user.id', ondelete="CASCADE"), nullable=False)
    post_id = db.Column(db.Integer, db.ForeignKey('post.id', ondelete="CASCADE"), nullable=False)
        

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required



class UpdateProfile(FlaskForm):
    bio = TextAreaField('Who are You?.',validators = [Required()])
    submit = SubmitField('submit')

app/__init__.py
from flask import Flask, app
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import  SimpleMDE
from flask_login import LoginManager
from flask_bootstrap import Bootstrap



simple = SimpleMDE()



mail = Mail()



login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
def create_app(config_name):
    app = Flask(__name__)

    


    # Creating the app configurations

    app.config.from_object(config_options[config_name])
    # config_options[config_name].init_app(app)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    
    mail.init_app(app)
    simple.init_app(app)
    login_manager.init_app(app)
    
    


    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')

    # setting config
    

    configure_uploads(app,photos)


    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort,flash,jsonify
from . import main
from flask_login import login_required,current_user
from .. import db,photos
import markdown2
from ..request import get_quote
from .forms import  UpdateProfile
from ..models import User,Post,Comment,Like

@main.route("/")
@login_required
def home():
    quotes = get_quote()
    posts = Post.query.all()
    return render_template("index.html",quotes=quotes,user= current_user,posts = posts)



@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)






@main.route('/user/<uname>/update',methods = ['GET','POST'])
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.home',uname=uname))



@main.route("/delete-comment/<comment_id>")
@login_required
def delete_comment(comment_id):
    comment =Comment.query.filter_by(id=comment_id).first()


    if not comment:
        flash("Comment does not exist", category="error")
    elif current_user.id != comment.author and current_user.id != comment.post.author:
        flash("These comment can not be deleted",category="error")
    
    else:
        db.session.delete(comment)
        db.session.commit()


    return redirect(url_for('main.home'))



@main.route("/create-blog",methods =['GET','POST'])
@login_required
def create_blog():
    if request.method == 'POST':
        text = request.form.get('text')
        if not text:
            flash("Post can not be empty",category='error')

        else:
            post = Post(text=text,author =current_user.id)
            db.session.add(post)
            db.session.commit()

            flash('Post has been created successfully',category='success')

            return redirect(url_for('main.home'))
    return render_template('create_blog.html',user = current_user)

@main.route("/delete-post/<id>")
@login_required
def delete_post(id):
    post = Post.query.filter_by(id = id).first()
    if not post:
        flash("Post does not exist",category='error')

    
    else:
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted successfuly',category='success')
    return redirect(url_for('main.home'))


@main.route('/posts/<username>')
@login_required
def posts(username):
    user = User.query.filter_by(username=username).first()
    if not user:
        flash("user does not exist")
        return redirect(url_for('views.home'))
    posts = user.posts
    return render_template("posts.html",user=current_user,posts=posts,username = username)



@main.route("/create-comment/<post_id>", methods=['POST'])
@login_required
def create_comment(post_id):
    text = request.form.get('text')

    if not text:
        flash('Comment cannot be empty.', category='error')
    else:
        post = Post.query.filter_by(id=post_id)
        if post:
            comment = Comment(
                text=text, author=current_user.id, post_id=post_id)
            db.session.add(comment)
            db.session.commit()
        else:
            flash('Post does not exist.', category='error')

    return redirect(url_for('main.home'))

@main.route("/like-post/<post_id>", methods=['POST'])
@login_required
def like(post_id):
    post = Post.query.filter_by(id=post_id).first()
    like = Like.query.filter_by(
        author=current_user.id, post_id=post_id).first()

    if not post:
        return jsonify({'error': 'Post does not exist.'}, 400)
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        like = Like(author=current_user.id, post_id=post_id)
        db.session.add(like)
        db.session.commit()

    return jsonify({"likes": len(post.likes), "liked": current_user.id in map(lambda x: x.author, post.likes)})

app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"/>
    
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"/>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <title style="font-style: italic; color: rgba(121, 121, 21, 0.425);">{% block title %}
        Home
        {% endblock %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-warning">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar"><span class="navbar-toggler-icon"></span> </button>
     
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
        <a class="nav-item nav-link" id="home" href="/" > Home</a>
          {% if current_user.is_authenticated%}
          <a class="nav-item nav-link" id="logout" href="{{url_for('auth.logout')}}">Logout</a>
          <a  class="nav-item nav-link" id="profile" href="{{url_for('main.profile',uname=current_user.username)}}" >Profile</a>
          {% else %}

          <a class="nav-item nav-link" id="login" href="{{url_for('auth.login')}}">Login</a>
          <a class="nav-item nav-link" id="sign-up" href="{{url_for('auth.sign_up')}}">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} 
    {% endfor %}
     {% endif %}
      {% endwith %}



<style>
    #home{
        color: rgb(50, 90, 10);
        font-size: 1.2rem;
        font-style: italic;
    }
    #logout{
        color: rgb(50, 90, 10);
        font-size: 1.2rem;
        font-style: italic;
    }
    #sign-up{
        color: rgb(50, 90, 10);
        font-size: 1.2rem;
        font-style: italic;
    }
    #login{
        color: rgb(50, 90, 10);
        font-size: 1.2rem;
        font-style: italic;
    }
    #profile{
        color: rgb(50, 90, 10);
        font-size: 1.2rem;
        font-style: italic;
    }
    
</style>



    <div class="container">
        {% block content %}
         {% endblock %}</div>

    <script  src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


    <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    
  
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"crossorigin="anonymous"></script>
    
 
    
  <script type="text/javascript" src="{{ url_for('static', filename='index.js')}}"></script>
  
  

app/templates/create_blog.html
{% extends "base.html" %}
{% block title%}{% endblock %}
{% block content %}

<body>
       
    <style>
    body{
        background: url("{{ url_for('static',filename='images/img3.jpg') }}") center/cover no-repeat;}
    </style>




<h1 align = center style="text-transform: uppercase; color: rgb(165, 112, 47); font-style: italic; font-family: 'Courier New', Courier, monospace;">Post  Blog</h1>
<form method="POST">
<div class="card" align="center" style="width: 45rem; height: 24rem;">
    <div class="card-body">
      <h5 class="card-title" style="font-style: italic; font-family: 'Courier New', Courier, monospace; color: rgb(161, 105, 36);">Post a Blog</h5>
      <p class="card-text"><textarea name="text" id="text" class="form-control"></textarea></p>
      <div align=center>
        <button type="submit" class="btn btn-success" >Post</button>
        </div>
      
    </div>
  </div>
</form>

<div >
    <a href="{{url_for('main.home')}}"><button type="button" class="btn btn-lg btn-primary">Back</button></a>
</div>



<style>

.card{

    background-color: azure;
}


</style>

{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
 {% block title %}
 Home
 {% endblock %}
  {% block content%}
  
  <body>
       
    <style>
    body{
        background: url("{{ url_for('static',filename='images/img4.jpg') }}") center/cover no-repeat;}
    </style>

  
  <h1 align="center" style="color: rgb(201, 143, 36); font-size: 1.8rem;">{% block header %}Blogs{% endblock %}</h1>
  
  <div id="posts" class="">
    
    {% for post in posts %}
    <div  id="posted" class="card border-dark " style="width: 50vw;">
      <div class="card-header d-flex justify-content-between align-items-center" >
        <h6 style="font-style: italic; font-size: 1.2rem; color:rgb(201, 143, 36) ;">{{post.user.username}}</h6>
        <div>
          <span id="likes-count-{{post.id}}">
          {{ post.likes|length }}</span> 
          {% if user.id in post.likes|map(attribute="author")|list %}
          <i class="bi bi-heart" style="color: rgb(177, 42, 42);" id="like-button-{{post.id}}" onclick="like({{post.id}})"></i>
          {% else %}
          <i class="bi bi-heart" id="like-button-{{post.id}}" onclick="like({{post.id}})"></i>  
          {% endif %} {% if user.id == post.author %}
          <div class="btn-group"><button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-bs-toggle="dropdown"></button>  
            <ul class="dropdown-menu" style="background-color: rgb(23, 112, 62); border: none;">
              <li>
                <a href="/delete-post/{{post.id}}" class="dropdown-item" style="font-style: italic;color: rgb(201, 143, 36); ">Delete</a>
              </li>
            </ul>
          </div>
          {% endif %}
        </div>
      </div>
      <div class="card-body">
        <div class="containered">
        <div class="carded">
          <div class="face face1">
            <div class="content">
              <span class="stars"></span>
              <a href="/"><h2 class="cSharp">{{quotes.author}}</h2></a>
              <p class="sharp">{{quotes.quote}}</p>
            </div>
            
          </div>
        </div>
        </div>
        <div class="card-text" style="color: rgb(23, 112, 62); font-size: 1.3rem; font-style: italic; text-transform: capitalize;">{{post.text}}</div>
        <br>
        <div class="collapse" id="comments-{{post.id}}">
          <div class="card">
            <div class="card-body" id="comments-expanded-{{post.id}}">
              {% for comment in post.comments %}
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <a href="/posts/{{comment.user.username}}"
                    >{{comment.user.username}}</a>
                  : {{comment.text}}
                </div>
                <div>
                  <p class="text-muted">{{comment.date_created.today().strftime('%Y-%m-%d %H;%M')}}</p>
                  {% if user.id == comment.author or user.id == post.author %}
                  <div class="btn-group"><button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-bs-toggle="dropdown"></button> 
                    <ul class="dropdown-menu">
                      <li>
                        <a href="/delete-comment/{{comment.id}}" class="dropdown-item">Delete</a>
                      </li>
                    </ul>
                  </div>
                  {% endif %}
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        <p class="card-text">
          {% if post.comments|length > 0 %}
          <a data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
            <p>View {{post.comments|length}} Comments</p>
          </a>
          {% else %}
          <p class="text-muted" style="font-style: italic; color: rgb(20, 201, 98); font-family: 'Koh Santepheap', cursive;">No Comments</p>
          {% endif %}
        </p>
        <form class="input-group mb-3" method="POST"  action="/create-comment/{{post.id}}">
          <input type="text" id="text" name="text" class="form-control" placeholder="write a comment">
          <button type="submit" class="btn btn-primary">Comment</button>
        </form>
      </div>
      <div  class="card-footer text-muted" style="background-color: black; color: rgb(24, 124, 91);"> Posted on: {{post.date_created.today().strftime('%Y-%m-%d %H;%M')}}</div>
    </div>
    
    <br> {% endfor %}
  </div>
  {% block footer %}
  <div align="center">
    <a href="/create-blog"><button type="button" class="btn" > Create a blog </button></a>
  </div>


  <style>
    .btn{
      background-color: rgb(201, 143, 36);
      text-transform: capitalize;
      font-style: italic;
      color: rgb(25, 133, 122);
      font-family: 'Koh Santepheap', cursive;
    }
    .btn:hover{
      background-color: rgb(124, 15, 124);
    }


    @import url("https://fonts.googleapis.com/css2?family=Righteous&display=swap");
    .containered{
      max-width: 100vw;
      display: grid;
      grid-template-columns: repeat(auto-fit,minmax(300px,1fr));
      grid-gap: 35px;
      margin: 0 auto;
      padding: 40px 0;

    }
    .carded{
      position: relative;
      width: 300px;
      height: 400px;
      margin: 0 auto;
      background: #000;
      border-radius: 14px;
      box-shadow: 0 15px 50px rgba(0, 0,0, 0.5);

    }

    .face{
      box-sizing: border-box;
      padding: 20px;

    }
    h2{
      margin: 0;
      padding: 0;
      font-size: 1.2em;
      font-style: italic;
      color: rgb(216, 226, 216);
      transition: 0.5s;
      text-shadow: 0 2px 5px rgba(0, 0,0, 0.3);
      z-index: 10;


    }
    .sharp{
      background-color:  #36b9ae;
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;

    }
    .user{
      font-size: 1rem;
      font-family: 'Courier New', Courier, monospace;
      font-style: italic;
    }
    
  
    #posted{
      background: url("{{ url_for('static',filename='images/img2.jpg') }}") center/cover no-repeat;
    }
    
    

    
  </style>
  {% endblock %} 
  {% endblock %}
  
  

app/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <form method="POST">
      <h3 align="center">Login</h3>
    <div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
      <div class="card card0 border-0">
          <div class="row d-flex">
              <div class="col-lg-6">
                  <div class="card1 pb-5">
                      <div class="row"> <img src="//unsplash.it/400/400" class="logo img-fluid rounded-circle"> </div>
                      <div class="row px-3 justify-content-center mt-4 mb-5 border-line"> <img src="//unsplash.it/400/400" class="image img-fluid rounded-circle"> </div>
                  </div>
              </div>
              <div class="col-lg-6">
                  <div class="card2 card border-0 px-4 py-5">
                      <div class="row mb-4 px-3">
                          <h6 class="mb-0 mr-4 mt-2">Sign in with</h6>
                          <div class="facebook text-center mr-3">
                              <div class="fa fa-facebook"></div>
                          </div>
                          <div class="twitter text-center mr-3">
                              <div class="fa fa-twitter"></div>
                          </div>
                          <div class="linkedin text-center mr-3">
                              <div class="fa fa-linkedin"></div>
                          </div>
                      </div>
                      <div class="row px-3 mb-4">
                          <div class="line"></div> <small class="or text-center">Or</small>
                          <div class="line"></div>
                      </div>
                      <div class="row px-3"> <label class="mb-1">
                              <h6 class="mb-0 text-sm">Email Address</h6>
                          </label> <input class="mb-4" type="text" name="email" id="email" placeholder="Enter a valid email address"> </div>
                      <div class="row px-3"> <label class="mb-1">
                              <h6 class="mb-0 text-sm">Password</h6>
                          </label> <input type="password" name="password" class="form-control" placeholder="Enter password"> </div>
                      <div class="row px-3 mb-4">
                          <div class="custom-control custom-checkbox custom-control-inline"> <input id="chk1" type="checkbox" name="chk" class="custom-control-input"> <label for="chk1" class="custom-control-label text-sm">Remember me</label> </div> <a href="#" class="ml-auto mb-0 text-sm">Forgot Password?</a>
                      </div>
                      <div class="row mb-3 px-3"> <button type="submit" class="btn btn-blue text-center">Login</button> </div>
                      <div class="row mb-4 px-3"> <p class="font-weight-bold">Don't have an account? <a class="text-danger " href="{{url_for('auth.sign_up')}}">Register</a></p> </div>
                  </div>
              </div>
          </div>
          <div class="bg-blue py-4">
              <div class="row px-3"> <small class="ml-4 ml-sm-5 mb-2">Copyright &copy; 2019. All rights reserved.</small>
                  <div class="social-contact ml-4 ml-sm-auto"> <span class="fa fa-facebook mr-4 text-sm"></span> <span class="fa fa-google-plus mr-4 text-sm"></span> <span class="fa fa-linkedin mr-4 text-sm"></span> <span class="fa fa-twitter mr-4 mr-sm-5 text-sm"></span> </div>
              </div>
          </div>
      </div>
  </div>

      
    </form>



    <style>
body {
    color: #000;
    overflow-x: hidden;
    height: 100%;
    background-color: #B0BEC5;
    background-repeat: no-repeat
}

.card0 {
    box-shadow: 0px 4px 8px 0px #757575;
    border-radius: 0px
}

.card2 {
    margin: 0px 40px
}

.logo {
    width: 200px;
    height: 100px;
    margin-top: 20px;
    margin-left: 35px
}

.image {
    width: 360px;
    height: 280px
}

.border-line {
    border-right: 1px solid #EEEEEE
}

.facebook {
    background-color: #3b5998;
    color: #fff;
    font-size: 18px;
    padding-top: 5px;
    border-radius: 50%;
    width: 35px;
    height: 35px;
    cursor: pointer
}

.twitter {
    background-color: #1DA1F2;
    color: #fff;
    font-size: 18px;
    padding-top: 5px;
    border-radius: 50%;
    width: 35px;
    height: 35px;
    cursor: pointer
}

.linkedin {
    background-color: #2867B2;
    color: #fff;
    font-size: 18px;
    padding-top: 5px;
    border-radius: 50%;
    width: 35px;
    height: 35px;
    cursor: pointer
}

.line {
    height: 1px;
    width: 45%;
    background-color: #E0E0E0;
    margin-top: 10px
}

.or {
    width: 10%;
    font-weight: bold
}

.text-sm {
    font-size: 14px !important
}

::placeholder {
    color: #BDBDBD;
    opacity: 1;
    font-weight: 300
}

:-ms-input-placeholder {
    color: #BDBDBD;
    font-weight: 300
}

::-ms-input-placeholder {
    color: #BDBDBD;
    font-weight: 300
}

input,
textarea {
    padding: 10px 12px 10px 12px;
    border: 1px solid lightgrey;
    border-radius: 2px;
    margin-bottom: 5px;
    margin-top: 2px;
    width: 100%;
    box-sizing: border-box;
    color: #2C3E50;
    font-size: 14px;
    letter-spacing: 1px
}

input:focus,
textarea:focus {
    -moz-box-shadow: none !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
    border: 1px solid #304FFE;
    outline-width: 0
}

button:focus {
    -moz-box-shadow: none !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
    outline-width: 0
}

a {
    color: inherit;
    cursor: pointer
}

.btn-blue {
    background-color: #1A237E;
    width: 150px;
    color: #fff;
    border-radius: 2px
}

.btn-blue:hover {
    background-color: #000;
    cursor: pointer
}

.bg-blue {
    color: #fff;
    background-color: #1A237E
}

@media screen and (max-width: 991px) {
    .logo {
        margin-left: 0px
    }

    .image {
        width: 300px;
        height: 220px
    }

    .border-line {
        border-right: none
    }

    .card2 {
        border-top: 1px solid #EEEEEE !important;
        margin: 0px 15px
    }
}




    </style>



    {% endblock %}

app/templates/macros.html
{% macro displayMovieList(movie_list) %}

    

{% endmacro %}

<!-- Displaying reviews macro -->
{% macro displayReviews(review_list) %}

    {% for review in review_list %}

    <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 review-card">
        <h2> {{ review.title}} </h2>
        <p> {{ review.review | truncate(30) }}</p>




    </div>
    {% endfor %}

{% endmacro %}

app/templates/posts.html
{% extends "index.html" %} 
{% block title %}
{{username}}'s
Posts
{% endblock %} 
    {% block header %}
     {{username}}'s
      posts 
      {% endblock %}
       {% block footer %}
    <div align="center">
      <a href="/home">
        <button type="button" class="btn btn-primary btn-lg">Back</button></a>
    </div>
    {% endblock %}

app/templates/profile/profile.html
<style>
  body{
      background: url("{{ url_for('static',filename='images/ted.jpg') }}") center/cover no-repeat;}
  </style>

{% if user == current_user %}

    <a href="{{url_for('main.update_profile',uname =user.username)}}">Edit profile</a>

{% endif %}


<div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="image img-fluid rounded-circle">
    {% else %}
    <p>No profile picture</p>
    {% endif %}

    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="POST" enctype = "multipart/form-data">

        <input type="file"  name="photo" class="form-control" required>
        <input type="submit">
      </form>
        {% endif %}

</div>

app/templates/profile/update.html
<style>
  body{
      background: url("{{ url_for('static',filename='images/img5.jpg') }}") center/cover no-repeat;}
  </style>

{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}